title: Žarko Stanković
email: stankovic.zarko@gmail.com
description: >-
  A software engineering blog.
  I write about the best programming practices gained through my development career
  and topics that are of my particular interest.
twitter_username: zarkostankovic
github_username:  ManInTheBox
linkedin_username: zarkostankovic
rss: rss
disqus:
  shortname: zarkostankovic
google_analytics: UA-114728204-1

show_excerpts: true

permalink: /:year/:month/:day/:title

minima:
  date_format: "%B %-d, %Y"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
